# Generated by Django 5.1.1 on 2024-09-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='checked',
            new_name='af',
        ),
    ]
